### ISSUE TITLE
terraform-rhcs-rosa-classic　sub module version requirment doesn't match with other sub modules. te

### ISSUE THREAD

**Issue by yuhkih** [terraform-redhat/terraform-rhcs-rosa-classic#77]
Hello.

Only "account-aim-resources" sub-module requires "version **=** 1.6.2-prerelese.1" while other sub-modules require "version **=** 1.6.2".

So, it seems that the "account-aim-resources" sub-module can't be used with other sub-modules because there is no provider that can satisfy these two requirements at the same time. 

Would it be possible to change the "account-aim-resources" requirement to "version **>=** 1.6.2-prerelese.1"?

**Comment by gdbranco** [comment]
Non stable version only work with specific operator (=), the modules have been update since the release of the stable version though. Closing this issue, if this is still an issue for you please consider updating the module version or reopening this issue with new information
