### ISSUE TITLE
Expected length of thumbprint_list.0 to be in the range (40 - 40) in submodule oidc-config-and-provider.

### ISSUE THREAD

**Issue by megharande** [terraform-redhat/terraform-rhcs-rosa-classic#79]
In oidc-config-and-provider submodule of rosa-classic module I am facing below thumbprint issue.

 Error: expected length of thumbprint_list.0 to be in the range (40 - 40), got
│
│   with module.rosa-classic.module.oidc_config_and_provider[0].aws_iam_openid_connect_provider.oidc_provider,
│   on .terraform/modules/rosa-classic/modules/oidc-config-and-provider/main.tf line 18, in resource "aws_iam_openid_connect_provider" "oidc_provider":
│   18:   thumbprint_list = [rhcs_rosa_oidc_config.oidc_config.thumbprint]

**Comment by gdbranco** [comment]
Resolved by https://github.com/terraform-redhat/terraform-provider-rhcs/pull/768
